1 5sp estructura principal de la aplicación
iesalonsodemadrigal/android-avila-diary pull request #12
Opened 2023-01-10 23:18 UTC by DavidCaidas

## Description de la tarea

añadida la navegacion de forma segura entre  los 5 apartados de la plicaion

## ¿Cómo se ha implementado?

añadidos en los gradle el binding y los navigation
creados todos los fragments para cada vista 
añadimos todos los values que vamos a usar en la carpeta res
creamos todos los layout
el boton del menú
y el nav graph
y en la main activity creamos las funciones 
el setup binding y el setup navigation

## Keywords

navigation, nav-graph, values, string, presentation, layout, fragments

## Screenshots or Video

https://user-images.githubusercontent.com/104197044/211682280-8eac8318-795e-4bd9-bdd7-a6d930676899.mp4

## Objetivos

> * [ ]  Creación de un menú navigation con los fragmentos: diary, rss, information, events, profile.
> * [ ]  Navegación segura entre los cinco fragmentos.
> * [ ]  Hilt: Application y MainActivity

2023-01-10 23:22 UTC, DavidCaidas commented
disclaimer:
me falta editar los iconos correctamente para que sean distintos, cogí uno de ejemplo que usé para todos

2023-01-11 10:58 UTC, MiM14 approved these changes
Buenas David. 
He revisado tu pr y he dejado un par de comentarios de un par de cosas que he visto, sin embargo, buen trabajo con la PR. Lo importante esta bien hecho sigue así. 🚀

2023-01-11 10:58 UTC, MiM14 commented on .idea/gradle.xml
> +  <component name="GradleMigrationSettings" migrationVersion="1" />
El gitignore no esta bien
Os dejo el enlace del que uso yo:
https://github.com/github/gitignore/blob/main/Android.gitignore

2023-01-11 10:58 UTC, MiM14 commented on app/src/main/res/layout/fragment_information.xml
> +        android:textSize="30sp"
acuérdate del fichero dimens. Entiendo que es un texto que se va a retirar, pero cuidado en futuras pr

2023-01-11 11:05 UTC, alvarogo1998 approved these changes
PR Ok 🚀

2023-01-11 14:40 UTC, DavidCaidas commented on .idea/gradle.xml
> +  <component name="GradleMigrationSettings" migrationVersion="1" />
al toque mi rey
ahora lo cambio

2023-01-11 14:42 UTC, DavidCaidas commented on app/src/main/res/layout/fragment_information.xml
> +        android:textSize="30sp"
como es un texto que borraremos directamente a la que se editen las layout no pensé en meterlo a dimens ya que es un dato que desaparecerá

2023-01-11 14:51 UTC, jmperezra requested changes
No debería existir el directorio .idea

2023-01-11 14:59 UTC, DavidCaidas reviewed
quitado el .idea del repositorio

2023-01-11 15:29 UTC, jmperezra requested changes
Revisa un par de comentarios

2023-01-11 15:29 UTC, jmperezra commented on app/src/main/java/com/iesam/aviladiary/MainActivity.kt
> +        findViewById<BottomNavigationView>(R.id.bottom_menu).setOnItemSelectedListener {
Si estamos usando viewBinding, no tiene sentido usar findViewById

2023-01-11 15:29 UTC, jmperezra commented on app/src/main/res/menu/bottom_menu.xml
> +    <item android:id="@+id/diary_item"
El orden de los items es:
- Eventos de las agendas
- Eventos privados
- Rss
- Información
- Profile

2023-01-11 15:42 UTC, DavidCaidas commented on app/src/main/res/menu/bottom_menu.xml
> +    <item android:id="@+id/diary_item"
ahora cambio el orden de los botones

2023-01-11 17:52 UTC, DavidCaidas commented on app/src/main/java/com/iesam/aviladiary/MainActivity.kt
> +        findViewById<BottomNavigationView>(R.id.bottom_menu).setOnItemSelectedListener {
ya hice los cambios y sustituí el find view by id

2023-01-11 17:54 UTC, DavidCaidas commented
https://user-images.githubusercontent.com/104197044/211881484-f1d8d036-1b09-4d6d-afaa-c332a22e822b.mp4

pruebas gráficas de el cambio de orden en information y profile

2023-01-12 11:30 UTC, josem-perram requested changes
David, creo que no quedó claro el tema de los idiomas, en los strings.xml debe ir en español. Gracias

2023-01-12 11:30 UTC, josem-perram commented on app/src/main/res/values/strings.xml
> +    <string name="profile_fragment_title">Profile</string>
Debemos ponerlo en español: Perfil, Rss, Eventos, Agenda...

2023-01-12 11:34 UTC, DavidCaidas commented on app/src/main/res/values/strings.xml
> +    <string name="profile_fragment_title">Profile</string>
ahora mismo los cambio

2023-01-12 11:35 UTC, DavidCaidas commented on app/src/main/res/values/strings.xml
> +    <string name="profile_fragment_title">Profile</string>
mantengo Rss o  lo llamo Noticias ?
Cual consideras que informa mejor a los usuarios ?

2023-01-12 11:40 UTC, DavidCaidas commented on app/src/main/res/values/strings.xml
> +    <string name="profile_fragment_title">Profile</string>
voy a mantener los 2 por el momento

2023-01-12 15:12 UTC, josem-perram approved these changes
👍

2023-01-12 15:14 UTC, alvarogo1998 submitted a review, later dismissed

2023-01-12 15:33 UTC, MiM14 approved these changes
🚀

2023-01-12 15:42 UTC, alvarogo1998 approved these changes
👍

2023-01-12 15:46 UTC, DavidCaidas commented
los cambios añadidos en esta nueva revision son cambios que ya han sido revisados en una anterior PR pero necesito el approve para mergear esta rama

2023-01-12 16:02 UTC, MiM14 approved these changes
✅

2023-01-12 16:02 UTC, MiM14 commented on app/src/main/java/com/iesam/aviladiary/Events/domain/EventFeedUseCase.kt
> +import com.iesam.app.domain.functional.right
Estos imports no te hacen falta (El Right y el Left)

2023-01-12 16:03 UTC, DavidCaidas commented on app/src/main/java/com/iesam/aviladiary/Events/domain/EventFeedUseCase.kt
> +import com.iesam.app.domain.functional.right
ahora os borro

2023-01-12 16:03 UTC, merged