Events data remote
iesalonsodemadrigal/android-avila-diary pull request #28
Opened 2023-01-13 18:48 UTC by Pabloyquemas

## Description de la tarea

Implementacion remotesource

## ¿Cómo se ha implementado?

He creado un objeto **EventsRemoteModule** que contiene dos proveedores **provideretrofit** que contiene el retrofitBuilder y otro proveedor **provideApiService** que contiene los apiservice que luego inyecto en la clase **EventsApiClient**, en los dos proveedores puse un singleton para que solo lo instancie una unica vez ,actualice el naming de varias funciones a suspendidas para posteriormente poder utilizar coorutinas.

## Keywords

clase, inject, provide, singleton

## Screenshots or Video

## Objetivos

## Criterios de Evaluación

2023-01-16 10:55 UTC, MiM14 requested changes
Arregla los errores de Merge que tienes en tu capa de dominio

2023-01-16 10:55 UTC, MiM14 commented on app/src/main/java/com/iesam/aviladiary/MainActivity.kt
> +import kotlinx.coroutines.GlobalScope
Cuidado con estos imports para probar cosas

2023-01-17 09:18 UTC, jmperezra requested changes
@Pabloyquemas la semana pasada os pasé código para que pudieras copiar y pegar en vuestro proyecto y con ello gestionar Hilt en remoto y las excepciones con apenas tres o cuatro líneas. Aquí no se ve. Por favor, revisa [los apuntes](https://iesam-dam.github.io/programacion-servicios-procesos/works-units/libraries/retrofit.html#retrofit-y-hilt)

2023-01-17 09:18 UTC, jmperezra commented on app/src/main/java/com/iesam/app/di/EventsDataRemoteModule.kt
> +object EventsDataRemoteModule {
Esto no debería llevar asociado ningún nombre de una feature, mejor usar algo genérico tipo: RemoteModule.

2023-01-17 09:18 UTC, jmperezra commented on app/src/main/java/com/iesam/app/di/EventsDataRemoteModule.kt
> +            .baseUrl("https://aviladiary.sitehub.es/api/v1/")
Mejor en una constante, revisa el repositorio superheroes

2023-01-17 09:18 UTC, jmperezra commented on app/src/main/java/com/iesam/app/di/EventsDataRemoteModule.kt
> +    fun provideApiService(retrofit: Retrofit):EventsApiService{
Esto es lo que debería ir en la carpeta de cada una de las features, revisa el repo SuperHero

2023-01-17 09:18 UTC, jmperezra commented on app/src/main/java/com/iesam/aviladiary/events/data/remote/EventsApiClient.kt
> +    fun getEventsFeed(): Either<ErrorApp, List<EventsApiModel>>  {
Deberías usar lo que vimos la semana pasada sobre Hilt, Remote y Gestión de Excepciones.

2023-01-17 12:20 UTC, Pabloyquemas commented
Ya cambie todo basandome en los apuntes

2023-01-18 23:58 UTC, josem-perram submitted a review, later dismissed
Revisa los comentarios, problemas en la organización de paquetes.

2023-01-18 23:58 UTC, josem-perram commented on app/src/main/java/com/iesam/app/data/remote/di/AvilaDiaryProvidersModule.kt
> +package com.iesam.app.data.remote.di
La ubicación de esta clase debería ser app/di

2023-01-18 23:58 UTC, josem-perram commented on app/src/main/java/com/iesam/app/data/remote/di/AvilaDiaryProvidersModule.kt
> +    fun providesEventsService(retrofit: Retrofit): EventsApiService =
Esto se exclusivo de Events, así que debería ir en feature/events/di

2023-01-18 23:58 UTC, josem-perram commented on app/src/main/java/com/iesam/app/data/remote/di/RemoteModule.kt
> +package com.iesam.app.data.remote.di
Esto debería ir en app/di

2023-01-19 09:19 UTC, Pabloyquemas commented on app/src/main/java/com/iesam/app/data/remote/di/AvilaDiaryProvidersModule.kt
> +    fun providesEventsService(retrofit: Retrofit): EventsApiService =
pero en este module no deberian ir todos los servicios de las features?

2023-01-19 09:31 UTC, MiM14 approved these changes
Buen trabajo con la PR💪

2023-01-19 10:12 UTC, alvarogo1998 approved these changes
La PR esta bien.

2023-01-19 15:39 UTC, alvarogo1998 commented
🚀

2023-01-20 15:06 UTC, josem-perram approved these changes
🚀

2023-01-20 15:07 UTC, jmperezra approved these changes

2023-01-20 15:07 UTC, merged