15 profile listado de desarrolladores data remote
iesalonsodemadrigal/android-avila-diary pull request #37
Opened 2023-01-18 15:24 UTC by amrubio27

## Description de la tarea
Creacion del apartado Data/Remote de la feature Developers.
## ¿Cómo se ha implementado?
-Se han realizado la carpeta api con los correspondientes archivos.
-Se han creado los archivos DevelopersApiService, DevelopersDataRepository y DevelopersRemoteDataSource
## Keywords
Remote, Api, Developers, RetroFit

2023-01-18 15:47 UTC, DavidCaidas requested changes
![Captura de pantalla 2023-01-18 163903](https://user-images.githubusercontent.com/104197044/213219197-d51668cf-d76d-4adf-89b4-3d61d046d9d8.png)

2023-01-18 15:47 UTC, DavidCaidas commented on app/src/main/java/com/iesam/app/data/remote/di/AvilaDiaryProvidersModule.kt
> +
te tienes que añadir aquí tu parte

2023-01-18 15:47 UTC, DavidCaidas commented on app/src/main/java/com/iesam/aviladiary/developers/data/remote/api/DevelopersApiRemoteDataSource.kt
> +        }.right()
este fragmento de código nos dijo chema que estaba mal,
la sintaxis que deberíamos usar es esta:

        return apiCall {
           (tu apiservice).(tuFuncionGetAll())
        }.map {
            it.map{
                it.toDomain()
            }
        }

2023-01-18 16:07 UTC, amrubio27 commented on app/src/main/java/com/iesam/aviladiary/developers/data/remote/api/DevelopersApiRemoteDataSource.kt
> +        }.right()
ok, realizados los cambios.

2023-01-18 17:38 UTC, DavidCaidas requested changes
revisa los comentarios
![6d26a7de12a5c6fe9e3f85091d73bdf6](https://user-images.githubusercontent.com/104197044/213254390-0e51c0cc-9423-43a8-8b89-1cd8da344a38.jpg)

2023-01-18 17:38 UTC, DavidCaidas commented on app/src/main/java/com/iesam/app/data/remote/di/AvilaDiaryProvidersModule.kt
> +}
@Singleton
    @Provides
    fun providesDevelopersService(retrofit: Retrofit): DevelopersApiService =
        retrofit.create(DevelopersApiService::class.java)
}


(este, este es tu código)


    @Singleton
    @Provides
    fun providesEventsService(retrofit: Retrofit): EventsApiService =
        retrofit.create(EventsApiService::class.java)

(este de aqui, es el de pablo)

no puedes editar el de Pablo, tienes que añadir el tuyo debajo

2023-01-18 20:15 UTC, amrubio27 commented on app/src/main/java/com/iesam/app/data/remote/di/AvilaDiaryProvidersModule.kt
> +}
ok ya esta de vuelta la linea

2023-01-19 00:01 UTC, josem-perram requested changes
@amrubio27 revisa los comentarios. La PR en tema de organización es un poco caótica ya que hay cosas que no son de tu tickets como los eventos (Pablo) o cosas que ya están corregidas en otra PR.

2023-01-19 00:01 UTC, josem-perram commented on app/src/main/java/com/iesam/aviladiary/events/data/EventsDataRepository.kt
> +class EventsDataRepository @Inject constructor(private val remotesource: EventRemoteDataSource):EventRepositories {
Eventos en esta PR ??

2023-01-19 08:41 UTC, DavidCaidas commented on app/src/main/java/com/iesam/aviladiary/events/data/EventsDataRepository.kt
> +class EventsDataRepository @Inject constructor(private val remotesource: EventRemoteDataSource):EventRepositories {
los eventos es porque sacó la rama de una de pablo que tenía archivos comunes para todos nosotros
como la está comparando a develop salen los archivos
cuando se haga merge a la de pablo no habrá archivos de Events

2023-01-19 09:26 UTC, Joelgh1 requested changes
Revisa los comentarios

2023-01-19 09:26 UTC, Joelgh1 commented on app/src/main/java/com/iesam/app/data/remote/di/AvilaDiaryProvidersModule.kt
> +
Estos provides deberían ir en la feature a la que correspondan

2023-01-19 09:26 UTC, Joelgh1 commented on app/src/main/java/com/iesam/app/domain/domain/ErrorApp.kt
>      class DomainError(): ErrorApp()
Si el resto de errores son object sería coherente que el DomainError también lo fuese

2023-01-19 17:53 UTC, amrubio27 commented on app/src/main/java/com/iesam/app/data/remote/di/AvilaDiaryProvidersModule.kt
> +
ok. He creado una carpeta 'di' en mi feature con el archivo 'DevelopersProvidersModule' en la que he implementado mi parte del código en él. Deberia estar bien ahora.
Tambien he borrado ese codigo del anterior 'di'.

![image](https://user-images.githubusercontent.com/114093648/213514406-4ff9f90d-699d-490b-aed9-a6dabce5a6d2.png)

2023-01-19 17:56 UTC, amrubio27 commented on app/src/main/java/com/iesam/aviladiary/developers/data/remote/DevelopersRemoteDataSource.kt
> +    suspend fun getAllDevelopers(): Either<ErrorApp, List<DevelopersModels>>
Es verdad que en mi caso siempre devuelve 'todos' los desarrolladores siempre y el 'All' sería redundante.

2023-01-19 18:04 UTC, amrubio27 commented on app/src/main/java/com/iesam/aviladiary/events/data/EventsDataRepository.kt
> +class EventsDataRepository @Inject constructor(private val remotesource: EventRemoteDataSource):EventRepositories {
Como ha dicho David, al hacer merge de la rama de Pablo para poder trabajar con las dependencias que habia realizado Pablo, me salen 25 archivos al realizar la PR. He puesto el WARNING para eso, por que tenemos que quedar de momento y actualizar la rama de Developer para poder trabajar bien con los cambios.

2023-01-19 18:47 UTC, DavidCaidas approved these changes
cambia el nombre de la funcion en todos los sitios para que no te dé fallo 
y a la que lo cambies lo veo todo bien

2023-01-19 18:47 UTC, DavidCaidas commented on app/src/main/java/com/iesam/aviladiary/developers/data/DevelopersDataRepository.kt
> +        return remoteDataSource.getDevelopers()
aqui no cambiaste el nombre de funcion 
se sigue llamando getAllDevelopers

2023-01-19 18:47 UTC, DavidCaidas commented on app/src/main/java/com/iesam/aviladiary/developers/data/remote/api/DevelopersApiRemoteDataSource.kt
> +            developersServices.getAllDevelopers()
el nombre de la funcion

2023-01-19 18:47 UTC, DavidCaidas commented on app/src/main/java/com/iesam/aviladiary/developers/domain/DevelopersUseCase.kt
> +        return developersRepository.getAllDevelopers()
aqui igual

2023-01-19 18:47 UTC, DavidCaidas commented
asegurate de mirar en el domain tambien por el nombre de la funcion

2023-01-19 18:56 UTC, amrubio27 commented on app/src/main/java/com/iesam/aviladiary/developers/domain/DevelopersUseCase.kt
> +        return developersRepository.getAllDevelopers()
LIsto. Ya he hecho el refactoring.

2023-01-19 19:03 UTC, DavidCaidas submitted a review, later dismissed
![Captura de pantalla 2023-01-19 200212](https://user-images.githubusercontent.com/104197044/213536458-715f1972-c6fd-4912-ae37-36f0f881df08.jpg)

2023-01-20 15:10 UTC, josem-perram approved these changes
Esta PR tiene que mejorar en cuanto a gestión, hay código que no debería estar aquí. En cuanto al desarrollo de la propia feature, se han corregido muchas cosas de las propuesta, me queda por ver PRs donde lleves tu la iniciativa. :)

2023-01-20 16:36 UTC, DavidCaidas approved these changes
fino
![image](https://user-images.githubusercontent.com/104197044/213753318-3e18034f-bb83-47fd-8702-86e8b1e86029.png)

2023-01-20 16:37 UTC, merged