Rss data remote
iesalonsodemadrigal/android-avila-diary pull request #38
Opened 2023-01-18 16:33 UTC by alvarogo1998

## Description de la tarea

Implementación de RemoteSource

## ¿Cómo se ha implementado?

Se ha creado el modulo **RemoteModule** con la implementación de Retrofit en un modulo de Hilt para poder proveernos de el, también se ha añadido **ResponseExt** en el cual controlaremos tanto el susccess como los errores o excepciones que puedan surgir, se ha creado un **AvilaDiaryProvidesModule** con el cual llamaremos a la api, tenemos una interface llamada **RssApiService** en la cual hemos implementado la funcion getAllRss para obtener un listado de Rss. Se han puesto las funciones suspendidas para utilizar posteriormente corrutinas, respecto a los 2 proveedores se ha añadido Singelton ya que solo queremos instanciarlo una única vez.

## Keywords

- Hilt
- Retrofit
- Singelton
- Corrutinas
- Mapper

## Screenshots or Video

![Remote](https://user-images.githubusercontent.com/114082652/213237515-2f02bc28-0f05-4fa4-88b2-cf69e7f62784.png)

## Objetivos

## Criterios de Evaluación

2023-01-18 17:25 UTC, Pabloyquemas commented on app/src/main/java/com/iesam/aviladiary/rss/data/remote/api/RssApiRemoteDataSource.kt
> +    }
Nos dijo chema que .get() es unicamente para tratarlo por la derecha y no por la izquierda de esta otra forma que te recomiendo es como te recomiendo ponerlo

return  apiCall {
            apiClient.getAllRss()
        }.map {
            it.map{
                  it.toDomain()
               }
        }

2023-01-18 17:27 UTC, Pabloyquemas requested changes
GG, revisa los comentarios

2023-01-19 00:03 UTC, josem-perram requested changes
Please, revisa los comentarios.

2023-01-19 00:03 UTC, josem-perram commented on app/src/main/java/com/iesam/aviladiary/rss/data/RssDataRepository.kt
> +package com.iesam.aviladiary.rss.data
el paquete correcto sería com.iesam.aviladiary.feature.rss.data

2023-01-19 00:03 UTC, josem-perram commented on app/src/main/java/com/iesam/aviladiary/rss/data/remote/api/RssApiRemoteDataSource.kt
> +        }.get().map {
Esto no es correcto, lo hemos visto esta tarde en clase.

2023-01-19 00:03 UTC, josem-perram commented on app/src/main/java/com/iesam/aviladiary/rss/data/remote/api/RssApiService.kt
> +    suspend fun getAllRss():  Response<List<RssApiModel>>
el All en el naming sobra, vale con un getRss

2023-01-19 00:03 UTC, josem-perram commented on app/src/main/java/com/iesam/aviladiary/rss/di/AvilaDiaryProvidesModule.kt
> +object AvilaDiaryProvidesModule {
No lo llames así, mejor RssProvidesModule

2023-01-19 00:03 UTC, josem-perram commented on app/src/main/java/com/iesam/aviladiary/rss/domain/RssRepository.kt
> +    suspend fun getAllRss(): Either<ErrorApp, List<Rss>>
el All sobra en el naming

2023-01-19 16:42 UTC, alvarogo1998 commented on app/src/main/java/com/iesam/aviladiary/rss/data/RssDataRepository.kt
> +package com.iesam.aviladiary.rss.data
dentro de la carpeta de feature metería todo lo de rss no?, no solo este archivo.

2023-01-19 20:22 UTC, dherranz1 reviewed
Parece haberse corregido la parte del retorno del apiCall, pero parece faltar el cambio del paquete comentado por Chema.

2023-01-20 09:26 UTC, Pabloyquemas submitted a review, later dismissed

2023-01-20 14:04 UTC, dherranz1 approved these changes
Parecen estar todos los cambios realizados :+1:

2023-01-20 14:23 UTC, Pabloyquemas approved these changes

2023-01-20 15:12 UTC, josem-perram approved these changes
En la PR hay código que ya se ha corregido en otras PRs, hay que tener cuidado con esto. Por lo demás, veo corregido muchas de las cosas solicitadas, me queda por PRs donde lleves tu la iniciativa.

2023-01-20 16:36 UTC, Pabloyquemas approved these changes

2023-01-20 16:45 UTC, Pabloyquemas approved these changes

2023-01-21 22:34 UTC, josem-perram approved these changes
Bien Álvaro 👍

2023-01-21 22:37 UTC, merged