Information data remote
iesalonsodemadrigal/android-avila-diary pull request #39
Opened 2023-01-18 17:51 UTC by DavidCaidas

## Description de la tarea

se pide implementar el apartado de data-remote de la pestaña information

## ¿Cómo se ha implementado?

se han añadido unas lineas más de codigo en el providersModule para que recoja tambien mis datos.
se han implemetado los ApiModel, ApiService, ApiMapper y el ApiRemoteDataSource para recoger en un repositorio general despues.
se han añadido también los datarepository y dataSource.

## Keywords

Api,remote, DataRemote, ApiModel

## DISCLAIMER

a esta PR no se le va a realizar el merge hasta que la PR #28 no se haya mergeado a develop para evitar conflictos en el código

## Criterios de Evaluación

    [ ] Implementar el DataRemote

2023-01-19 00:06 UTC, josem-perram requested changes
Please, revisa los cambios. La PR es un poco caos, hay muchas cosas duplicadas en todas las PR y cosas que no tienen nada que ver con el ticket como Events. Esto no puede pasar.

2023-01-19 00:06 UTC, josem-perram commented on app/src/main/java/com/iesam/app/data/local/db/AppDatabase.kt
> +        return retrofit.create(InformationApiService::class.java)
Esto debe ir ubicado en la propia feature.

2023-01-19 00:06 UTC, josem-perram commented on app/src/main/java/com/iesam/aviladiary/information/data/remote/InformationApiService.kt
> +    suspend fun getAllInformation(): Response<List<InformationApiModel>>
el All en el naming sobra, mejor getInfomations

2023-01-19 00:06 UTC, josem-perram commented on app/src/main/java/com/iesam/aviladiary/information/data/remote/InformationDataRepository.kt
> +    override suspend fun getAllInformation(): Either<ErrorApp, List<InformationModels>> {
el All sobra

2023-01-19 00:06 UTC, josem-perram commented on app/src/main/java/com/iesam/aviladiary/information/data/remote/InformationDataRepository.kt
> +
formatea el código, que no quede extra espacio

2023-01-19 00:06 UTC, josem-perram commented on app/src/main/java/com/iesam/aviladiary/information/data/remote/InformationRemoteDataSource.kt
> +    suspend fun getAllInformation(): Either<ErrorApp, List<InformationModels>>
el All sobra

2023-01-19 17:09 UTC, DavidCaidas commented on app/src/main/java/com/iesam/app/data/local/db/AppDatabase.kt
> +        return retrofit.create(InformationApiService::class.java)
lo pensamos hace un par de días y acordamos entre todo el equipo que a la que tengamos todos acabada la parte de data ibamos a hacer un refactor de las carpetas porque nos dimos cuenta que ahora era un caos, pero si empezabamos a cambiarlo todo independientemente iba a ser aún más caótico

2023-01-19 17:09 UTC, DavidCaidas commented on app/src/main/java/com/iesam/aviladiary/information/data/remote/InformationApiService.kt
> +    suspend fun getAllInformation(): Response<List<InformationApiModel>>
ya he cambiado todos los naming incluidos en el domain para evitar fallos

2023-01-19 17:10 UTC, DavidCaidas commented on app/src/main/java/com/iesam/aviladiary/information/data/remote/InformationDataRepository.kt
> +    override suspend fun getAllInformation(): Either<ErrorApp, List<InformationModels>> {
ahora lo cambio

2023-01-19 20:11 UTC, dherranz1 reviewed
He dejado algunas aportaciones. Hay código de varias features en esta PR. No sé si esto tiene código antiguo que tal vez ya está solventado...

2023-01-20 09:29 UTC, Pabloyquemas commented on app/src/main/java/com/iesam/aviladiary/events/data/remote/api/EventsApiRemoteDataSource.kt
> +        }.get().map {
acuerdate de cambiar esto, como nos dijo chema en clasee

2023-01-20 09:30 UTC, Pabloyquemas requested changes
buena PR, revisa el comentarioo

2023-01-20 14:30 UTC, dherranz1 commented on app/src/main/java/com/iesam/app/data/local/db/AppDatabase.kt
> +    }
He visto que hay dos proveedores de Singleton de retrofit, entiendo que este ya sobra y sería conveniente quitarlo

2023-01-20 15:22 UTC, josem-perram submitted a review, later dismissed
David, revisa los comentarios. La gestión del PR no termina de ser la correcta, hay muchas clases que no tienen nada que ver con tu feature, cosas que ya se han corregido y meten ruido en la PR porque no sabes qué hay que corregir. Tienes el approve pero las PR tienen que mejorar si se quiere conseguir el objetivo.

2023-01-20 17:37 UTC, Pabloyquemas submitted a review, later dismissed

2023-01-21 22:40 UTC, josem-perram requested changes
@DavidCaidas revisa un par de namings a ver si conseguimos con estos cambios mergear la PR.

2023-01-21 22:40 UTC, josem-perram commented on app/src/main/java/com/iesam/aviladiary/information/di/AvilaDiaryProvidersModule.kt
> +    fun providesRssService(retrofit: Retrofit): InformationApiService =
David, al menos cambio los nombres de los provides :P

2023-01-21 22:40 UTC, josem-perram commented on app/src/main/java/com/iesam/aviladiary/information/di/AvilaDiaryProvidersModule.kt
> +object AvilaDiaryProvidesModule {
Este nombre debería estar relacionado con tu feature, InformationProvidersModulo tanto como nombre del fichero como del objeto.

2023-01-23 09:15 UTC, dherranz1 approved these changes

2023-01-23 09:20 UTC, dherranz1 approved these changes

2023-01-24 16:14 UTC, Pabloyquemas approved these changes

2023-01-24 16:22 UTC, josem-perram approved these changes
👍

2023-01-24 17:40 UTC, merged