Events data local
iesalonsodemadrigal/android-avila-diary pull request #41
Opened 2023-01-20 15:21 UTC by Pabloyquemas

## Description de la tarea

Implementado la parte local de data con ROOM

## ¿Cómo se ha implementado?

**EventsDao**: es una interfaz en la implemente las marcas de con sus respectivos metodos **saveEvents** en el que guarda las entidades de la data class **EventsEntity**, **getAllEvents** es una select en la que guarda todos los eventos en sus respectivas columnas, y **updateEvents** actualiza la base de datos.

**EventsEntity**: en esta data class implemente las columnas que va a tener la base de datos poniendo como clave primaria el **id**, tambien defini dos variables constantes una **TABLE_NAME_EVENTS** y otra **EVENTS_ID**, la columna **lastDate** es para utilizarla como cache, en esta columna es donde tendra la hora en milisegundos para poder actualizar la tabla.

**EventsDbLocalDataSource**: en esta clase inyecte  la interfaz **EventsDao** para poder implementar sus funciones.

**EventsDataRepository**: en esta clase inyecto las dos interfaces **EventRemoteDataSource** y **EventsLocalDataSource** para utilizar las funciones de las interfaces.

## Keywords

ROOM, HILT, EITHER

## Screenshots or Video

## Objetivos

## Criterios de Evaluación

2023-01-21 22:46 UTC, josem-perram requested changes
Pablo, please, revisa los comentarios. Hay errores a la hora de ubicar las clases de hilt cuando estan en app (app/di) y a la hora de tratar los errores de remoto.

2023-01-21 22:46 UTC, josem-perram commented on app/src/main/java/com/iesam/app/data/local/di/LocalModule.kt
> +package com.iesam.app.data.local.di
la ubicación de este fichero debería ser app/di

2023-01-21 22:46 UTC, josem-perram commented on app/src/main/java/com/iesam/aviladiary/events/data/EventsDataRepository.kt
> +            if (events.isLeft()){
Si cada vez que hay un error devolvemos un listado vacio, para qué usamos either? como vamos a mostrar al usuario que se ha producido un error de conexión de internet? del servidor?

En este caso, debemos checkear si es Right para guardarlo en la caché. Di da error, debemos propagarlo.

2023-01-21 22:46 UTC, josem-perram commented on app/src/main/java/com/iesam/aviladiary/events/data/local/db/EventsDbLocalDataSource.kt
> +    private val currentTime = System.currentTimeMillis()
No podemos guardar el tiempo actual como un atributo porque este se inicializa al instanciar la clase. Esto quiere decir que, desde que se instancia la clase hasta que se hace el save pueden pasar minutos y estas guardando un tiempo irreal. Este currenTime debería ir justo cuando se necesita, en el save.

2023-01-24 16:30 UTC, josem-perram requested changes
Please, revisa los comentarios.

2023-01-24 16:30 UTC, josem-perram commented on app/src/main/java/com/iesam/app/di/LocalModule.kt
> +    fun provideEventDao(appDatabase: AppDatabase): EventsDao {
Esto va en la propia feature: app/feature/events/di/EventProviders

2023-01-24 17:35 UTC, Pabloyquemas commented
DISCLAIMER!!!! Movi toda la carpeta events dentro de feature por eso hay 20 archivos, solo mirar la parte de local

2023-01-24 22:46 UTC, josem-perram requested changes
@Pabloyquemas hay cosas de programación base que fallan como es el poder hacer una función que coja datos de local o de remoto. Mañana lo vemos.

2023-01-24 22:46 UTC, josem-perram commented on app/src/main/java/com/iesam/aviladiary/feature/events/data/EventsDataRepository.kt
> +        var events = localsource.getEvents()
@Pabloyquemas please, habla con @amrubio27 sobre la lógica de este método. Creo que a nivel de equipo contemplais que si local devuelve left o empty hay que ir a red.

2023-01-24 22:46 UTC, josem-perram commented on app/src/main/java/com/iesam/aviladiary/feature/events/data/EventsDataRepository.kt
> +                return ErrorApp.DataError.left()
No debemos crearnos errores nuevos, debemos propagarlos. Si remoto te devuelve ErrorApp.InternetConnectionError y tu metes la condición:
```
if (events.isLeft()){
                return ErrorApp.DataError.left()
```
Nunca, nunca le llegará a la capa de presentación el InternetConnectionError porque estás devolviendo DataError.

Please, @amrubio27 debería poder ayudarte con esta lógica. Si quieres tb lo vemos en clase.

2023-01-24 22:46 UTC, josem-perram commented on app/src/main/java/com/iesam/aviladiary/feature/events/di/ProvidersModule.kt
> +object ProvidersModule {
naming: EventsProvidersModule

2023-01-24 23:16 UTC, Pabloyquemas commented on app/src/main/java/com/iesam/aviladiary/feature/events/data/EventsDataRepository.kt
> +                return ErrorApp.DataError.left()
Si, mañana lo vemos en clase porque yo ya me estoy liando muchisimo

2023-01-24 23:21 UTC, Pabloyquemas commented on app/src/main/java/com/iesam/aviladiary/feature/events/data/EventsDataRepository.kt
> +        var events = localsource.getEvents()
Lo que quedamos en el grupo es comprobar si primero esta en local si devuelve left vaya a red y si en red manda left dar un error y si red no da error lo guarde en local, alomejor nos equivocamos y no deberiamos mandar error si red va por la izquierda, mañana lo hablamos porque tengo bastantes dudas respecto a eso

2023-01-25 15:03 UTC, Pabloyquemas commented on app/src/main/java/com/iesam/aviladiary/feature/events/di/ProvidersModule.kt
> +object ProvidersModule {
En la PR de presentation hare este cambio

2023-01-25 15:17 UTC, albertoag128 commented on app/src/main/java/com/iesam/app/data/local/db/AppDatabase.kt
> +
Esto esta perfecto Pablo, pero ten en cuenta que habra que añadir el resto de entidades del proyecto al igual que mas funciones abstractas para llamar a los daos. Pd: la primera letra de la funcion tiene que ir con minuscula, que sino se puede confundir con una clase

2023-01-25 15:35 UTC, albertoag128 requested changes
Te pido cambios para el naming que mencionaba Chema y tambien cambiar el metodo para adquirir del dao de app/data/local/db/AppDatabase

2023-01-26 15:37 UTC, amrubio27 approved these changes
Buena Pablo, me apunto un par de cosas para seguir con mi código.

2023-01-27 14:39 UTC, josem-perram approved these changes
👍

2023-01-27 14:47 UTC, albertoag128 approved these changes
Veo que ya has realizado todos los cambios solicitados y ya has fixeado los problemas con el ProvidersModule y los aspectos de Room. Buen trabajo!!

2023-01-27 14:48 UTC, merged