Information data local
iesalonsodemadrigal/android-avila-diary pull request #48
Opened 2023-01-24 15:33 UTC by DavidCaidas

> ## Description de la tarea
> Implementado la parte local de data de information con ROOM
> 
> ## ¿Cómo se ha implementado?
> InformationDao: es una interfaz en la implemente las marcas de con sus respectivos metodos 
saveInformation en el que guarda las entidades de la data class 
getInfomration es un select en El que guarda toda la informacion

> InformationDbLocalDataSource: en esta clase inyecte la interfaz InformationDao para poder implementar sus funciones.
> 
> INformationDataRepository: en estavan las dos interfaces InformationRemoteDataSource y InformationLocalDataSource para utilizar las funciones de las interfaces.
> 
> ## Keywords
> ROOM, HILT, EITHER

2023-01-24 15:35 UTC, DavidCaidas commented
***DISCLAIMER***
hay tantísimos commit porque he estado haciendo malavares para evitar que salgan 37 files changes y salgan solo los cambios de mi propia rama

2023-01-24 21:48 UTC, albertoh8 commented on app/src/main/java/com/iesam/aviladiary/information/data/local/db/InformationDao.kt
> +    @Insert(onConflict = REPLACE)
Aqui puedes poner un @Transaction por si hay un error mientras no se han terminado de pasar todos los datos

2023-01-24 21:54 UTC, albertoh8 submitted a review, later dismissed
👍 Esta todo bien, revisa el comentario.

2023-01-24 22:57 UTC, josem-perram requested changes
Please, revisa los comentarios y habla con tus compañeros sobre la lógica de obtener de local o de remoto.

2023-01-24 22:57 UTC, josem-perram commented on app/src/main/java/com/iesam/aviladiary/information/data/InformationDataRepository.kt
> +        return if (information.isLeft()) {
@DavidCaidas please, esto justo es lo que hemos estado viendo con @amrubio27 . @albertoh8 has dado el approved pero esto no está bien, estás de acuerdo ?

2023-01-24 22:57 UTC, josem-perram commented on app/src/main/java/com/iesam/aviladiary/information/data/local/db/InformationDao.kt
> +    @Insert(onConflict = REPLACE)
Eso se hace con un simple @Transaction debajo del @Insert

2023-01-24 22:57 UTC, josem-perram commented on app/src/main/java/com/iesam/aviladiary/information/data/local/db/InformationDbLocalDataSource.kt
> +    private val currentTime = System.currentTimeMillis()
Cuando guardamos el tiempo actual en un atributo de clase, este se guarda cuando se instancia un objeto. El tiempo que almacena no tiene por qué coincidir con el tiempo cuando se ejecuta saveInformation. Por tanto, lo más preciso posible es ejecutar este System.currentTimeMillis es dentro del propio método save.

2023-01-26 09:42 UTC, DavidCaidas commented on app/src/main/java/com/iesam/aviladiary/information/data/InformationDataRepository.kt
> +        return if (information.isLeft()) {
ya hice los cambios y ahora haré el commit

2023-01-26 14:41 UTC, closed without merging